services:
  rust-server:
    user: "${UID}:${GID}"
    build:
      context: ./docker/rust
    environment:
      RUST_LOG: rust_server=info,sqlx=warn # ログレベル設定
      DB_HOST: postgres # ローカルと分離
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    working_dir: /app/apps/rust-server
    volumes:
      - .:/app
    ports:
      - "3000:3000"
  postgres:
    build:
      context: ./docker/postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      # - ./docker/postgres/initdb:/docker-entrypoint-initdb.d # アプリ側で初期化する場合は不要

volumes:
  pgdata: